Socket Created
Traceback (most recent call last):
  File "light2.py", line 16, in <module>
    s.connect((host,port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 101] Network is unreachable
